#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute
app:
  resource:
    '../src/Shared/Infrastructure/Routing/routing.xml'

#index:
#  path: /mau
#  controller: App\Controller\Test\CheckController